# Generated by Django 3.2.12 on 2023-02-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
