# Generated by Django 3.2.12 on 2023-02-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_delete_project'),
        ('job', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('proposal', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('require_days', models.IntegerField()),
                ('milestone', models.CharField(max_length=300)),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.job_seeker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
