# Generated by Django 3.2.12 on 2023-02-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='duration',
        ),
    ]
