# Generated by Django 3.2.12 on 2023-02-13 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0006_auto_20230209_1127'),
        ('employer', '0002_employer_phone'),
        ('job', '0007_auto_20230208_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('rating', models.FloatField()),
                ('feedback', models.CharField(max_length=250)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('job_Seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.job_seeker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
