# Generated by Django 3.2.12 on 2023-02-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='job_Seeker',
            new_name='job_seeker',
        ),
    ]
