# Generated by Django 3.2.12 on 2023-02-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_rename_job_seeker_rating_job_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='feedback',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
