# Generated by Django 3.2.12 on 2023-02-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_rating_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='required_skill',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='skill',
            field=models.ManyToManyField(null=True, to='job.Required_Skill'),
        ),
    ]
