# Generated by Django 3.2.12 on 2023-02-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_auto_20230206_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
