# Generated by Django 3.2.12 on 2023-02-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0004_remove_job_seeker_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='job_seeker',
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='skill',
            field=models.ManyToManyField(null=True, to='job_seeker.Skill'),
        ),
    ]
